Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StellarVoteApp.Core.Models;
using StellarVoteApp.Core.Services.Contracts;
using StellarVoteApp.Data.Services.Contracts;

namespace StellarVoteApp.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private IVoteService voteService;
        private IUserService userService;

        public UserController(IVoteService voteService, IUserService userService)
        {
            this.voteService = voteService;
            this.userService = userService;
        }

        public async Task<IActionResult> Index()
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            var hasStellarAccount = await this.userService.HasUserVotingAccount(userId);
            UserAccountInformation userAccountInformation;
            if (hasStellarAccount)
            {
                var stellarAccount = await this.userService.GetAccountDetails(userId);
                userAccountInformation = await this.voteService.GetUserAccountInformation(stellarAccount.AccountId);
                ViewBag.UserAccountInformation = userAccountInformation;
            }

            return View(hasStellarAccount);
        }
    }
}

Controllers/VoteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MongoDB.Bson.IO;
using Newtonsoft.Json.Linq;
using StellarVoteApp.Core.Services.Contracts;
using StellarVoteApp.Data.Services.Contracts;
using StellarVoteApp.Models.ViewModels;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Configuration.Binder;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace StellarVoteApp.Controllers
{
    [Authorize]
    public class VoteController : Controller
    {
        private IVoteService voteService;
        private IUserService userService;
        private IUserNationalIDInformationService idService;
        private IJsonConverter jsonConverter;
        private IConfiguration config;

        public VoteController(
            IVoteService voteService, 
            IUserService userService, 
            IUserNationalIDInformationService idService, 
            IJsonConverter jsonConverter,
            IConfiguration config)
        {
            this.voteService = voteService;
            this.userService = userService;
            this.idService = idService;
            this.jsonConverter = jsonConverter;
            this.config = config;
        }

        public async Task<IActionResult> Index()
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            var hasStellarAccount = await this.userService.HasUserVotingAccount(userId);
            if (!hasStellarAccount)
            {
                return this.RedirectToAction("CreateAccount");
            }

            var candidates = this.config.GetSection("Candidates").Get<List<SelectListItem>>();
            var stellarAccount = await this.userService.GetAccountDetails(userId);
            var userAccountInformation = await this.voteService.GetUserAccountInformation(stellarAccount.AccountId);
            ViewBag.HasVoted = userAccountInformation.HasVoted;
            return View(new CandidatesViewModel(candidates));
        }

        [HttpPost]
        public async Task<IActionResult> SendVote(string value)
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var stellarAccount = await this.userService.GetAccountDetails(userId);

            var hashOfSendVoteTx = await this.voteService.SendVoteToken(stellarAccount.AccountId, stellarAccount.SecredSeed, value);
            var vm = new SendVoteViewModel(hashOfSendVoteTx, value);

            return View("SuccessfulVote", vm);
        }

        public IActionResult CreateAccount()
        {
            return View();
        }

        public IActionResult ViewResults()
        {
            return View();
        }

        public async Task<List<CandidateResultViewModel>> GetResults()
        {
            var candidatesNames = this.config.GetSection("Candidates")
                .Get<List<SelectListItem>>()
                .Select(x => x.Text)
                .ToList();

            var candidateResults = new List<CandidateResultViewModel>();
            var results = await this.voteService.GetElectionResults();

            foreach (var result in results)
            {
                var name = result.Key;
                var votes = result.Value;
                if (candidatesNames.Contains(name))
                {
                    candidateResults.Add(new CandidateResultViewModel(name, votes));
                }
            }

            return candidateResults;
        }

        [HttpPost]
        public async Task<JsonResult> CreateAccount([FromBody] JObject json)
        {
            var idCredentials = this.jsonConverter.DeserializeJson<IdCredentialsViewModel>(json.ToString());

            var idCredentialsExist = await this.userService.CheckIfIdCredentialsExist(idCredentials.IdNumber, idCredentials.CardNumber);
            if (idCredentialsExist)
            {
                return Json("This ID credentials were already used to create an account!");
            }
            var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var hasStellarAccount = await this.userService.HasUserVotingAccount(userId);
            if (hasStellarAccount)
            {
                return Json("The current user already has an account! Check your profile page for details!");
            }

            var isValidID = this.idService.CheckUserID(idCredentials.IdNumber, idCredentials.CardNumber);

            if (!isValidID)
            {
                return Json("Not valid ID Credentials!");
            }

            StellarAccountViewModel model = new StellarAccountViewModel();
            var stellarAccount = this.voteService.CreateUserAccount();
            
            var isActivated = await this.voteService.ActivateUserAccount(stellarAccount.AccountId, stellarAccount.SecredSeed);
            if (!isActivated)
            {
                return Json("Account activation failed! Try again!");
            }
            
            var isTrustCreated = await this.voteService.ChangeTrustVoteToken(stellarAccount.AccountId, stellarAccount.SecredSeed);

            if (isTrustCreated)
            {
                var receivedVoteToken = await this.voteService.SendVoteTokenToUser(stellarAccount.AccountId);
                if (!receivedVoteToken)
                {
                    return Json("There was a problem with the acquisition of the Vote token. Try again!");
                }
            }
            else
            {
                return Json("The Vote token create trustline transaction failed! Try again!");
            }

            await this.userService.SaveAccountDetails(userId, stellarAccount.AccountId, stellarAccount.SecredSeed);
            await this.userService.SetVotingAccountTrue(userId);
            await this.userService.SaveUserIdCredentials(idCredentials.IdNumber, idCredentials.CardNumber);

            var balances = await this.voteService.GetBalances(stellarAccount.AccountId);
            model.AccountId = stellarAccount.AccountId;
            foreach (var b in balances)
            {
                if (b.Asset.ToLower().Contains("native"))
                {
                    model.XLMBalance = b.BalanceString;
                }
                else
                {
                    model.VoteTokenBalance = b.BalanceString;
                }
            }

            return Json(model);
        }
    }
}

Views/Vote/CreateAccount.cshtml
@{
}

<h3 class="text-center">Create Voting Account</h3>

<div id="form" class="col-sm-12">
    <div class="card">
        <div class="card-header">
        </div>
        <div class="card-body card-block">
            <form autocomplete="off" asp-controller="Vote" asp-action="CreateAccount" method="" class="">
                <div class="form-group">
                    <label class=" form-control-label">National ID Number</label>
                    <input id="idnumber" type="text" placeholder="Enter National ID Number" class="form-control">

                    <span class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label class=" form-control-label">Number of National ID Card</label>
                    <input id="cardnumber" type="text" placeholder="Enter Number of National ID Card" class="form-control">

                    <span class="text-danger"></span>
                </div>
                <div class="card-footer">
                    <button id="create" type="button" class="btn btn-primary btn-sm">
                        <i class="fa fa-dot-circle-o"></i> Submit
                    </button>
                    <button type="reset" class="btn btn-danger btn-sm">
                        <i class="fa fa-ban"></i> Reset
                    </button>
                </div>
            </form>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-sm-12">
            <strong>
                <i>* We do not store your id information. We store only the hashed values of your National Id Number and Number of National ID Card in order to validate that this ID Credentials are going to be used only once. </i>
            </strong>
        </div>  
        <div class="col-sm-12">
            <i>* Your ID credentials are validated by the government ID database service in order to create your voting account.</i>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-sm-12">
            <i>* <a target="_blank" href="https://www.educative.io/edpresso/what-is-hashing">What is hashing or hashed values?</a></i>
        </div>
    </div>
</div>

<div id="spinner"  class="row">       
    <div class="col-sm-12">
        <br />
        <h4 class="text-center">Your voting account is being created...</h4>
        <br />
        <div class="loader"></div>
    </div>
</div>

<div id="error" class="row">
    <div class="col-sm-12">
        <h3>An error occured!</h3>
    </div>
</div>

<div id="created" class="row">
    <div class="col-sm-12">
        <h3 class="text-center">Your Voting Account has been created!</h3>
        <br />
        <h4 class="text-center" id="account-details">

        </h4>
    </div>
    <div class="col-sm-12">
        <img class="custom-img" src="~/images/pic1.png" alt="Alternate Text" />
    </div>
</div>
<div id="invalid" class="row text-center">
    <div class="col-sm-12">
        <h3 id="invalidtext" class="text-center"></h3>
    </div>
</div>


@section Scripts {
    <script src="~/js/vote/createVotingAccount.js"></script>
}

Views/Vote/Index.cshtml
@model StellarVoteApp.Models.ViewModels.CandidatesViewModel
@{
    var loading = "Loading...";
    bool hasVoted = ViewBag.HasVoted;
}

@if (!hasVoted)
{
    <div class="row">
        <div class="col-sm-12">
            <h3 class="text-center">
                Time to Vote
            </h3>
        </div>
    </div>

    <div class="col-sm-12">
        <div class="card">
            <div class="card-header">

            </div>
            <div class="card-body card-block">
                <form asp-controller="Vote" asp-action="SendVote" method="post" class="">
                    <div class="form-group">
                        <label class=" form-control-label">Choose the Candidate you want to vote for</label>
                        <select class="form-control" asp-for="Value" asp-items="Model.Candidates"></select>
                    </div>
                    <div class="card-footer">
                        <button id="sendvote" type="submit" class="btn btn-primary btn-sm" data-loading-text="<i class='icon-spinner icon-spin icon-large'></i> @loading">
                            <i class="fa fa-dot-circle-o"></i> Vote
                        </button>
                        <button type="reset" class="btn btn-danger btn-sm">
                            <i class="fa fa-ban"></i> Reset
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <br />
    <br />
    <br />
    <div style="margin-top: 55px;" class="row">
        <div class="col-sm-12">
            <img class="custom-img" src="~/images//pic4.png" alt="Alternate Text" />
        </div>
    </div>
}
else
{
    <div class="row">
        <div class="col-sm-12">
            <h3 class="text-center">
                You have already sent your vote!
            </h3>
            <h4 class="text-center">
                For more details check <strong><a asp-controller="User" asp-action="Index">Your Profile</a></strong>
            </h4>
        </div>
    </div>
}

@section Scripts {
    <script src="~/js/vote/sendVote.js"></script>
}

Views/Vote/SuccessfulVote.cshtml
@model StellarVoteApp.Models.ViewModels.SendVoteViewModel
@{
}

<div class="row">
    <div class="col-sm-12">
        <h3 class="text-center">Your vote was sent successfully!</h3>
        <br />
        <h4 class="text-center">Your vote - @Model.ChosenCandidateName</h4>
        <br />
        <h4 class="text-center">
            Your vote was recorded in the blockchain by transaction with Hash -
            <a target="_blank" href="https://stellar.expert/explorer/testnet/tx/@Model.TxHash">
                @Model.TxHash
            </a>
        </h4>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <img class="custom-img" src="~/images/pic3.png" alt="Alternate Text" />
    </div>
</div>

Views/Vote/ViewResults.cshtml
@{
}
<div id="spinner" class="row">
    <div class="col-sm-12">
        <h4 class="text-center">The Results are loading...</h4>
        <div class="loader"></div>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <h3 id="header" class="text-center"></h3>
    </div>
</div>
<br />
<div class="row">
    <div class="col-sm-6">
        <canvas id="myChart"></canvas>
    </div>
    <div class="col-sm-6">
        <canvas id="pieChart"></canvas>
    </div>
</div>
<br />
<br />
<div class="row">
    <div class="col-sm-12">
        <div id="results">
            
        </div>
    </div>
</div>

@section Scripts {
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
    <script src="~/js/vote/getResults.js"></script>
}